Collections:
  - Name: TSM
    README: configs/recognition/tsm/README.md
    Paper:
      URL: https://arxiv.org/abs/1811.08383
      Title: "TSM: Temporal Shift Module for Efficient Video Understanding"

Models:
  - Name: tsm_r50_1x1x8_50e_8xb16_kinetics400_rgb
    Config: configs/recognition/tsm/tsm_r50_1x1x8_50e_8xb16_kinetics400_rgb.py
    In Collection: TSM
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 100
      FLOPs: 32965562368
      Parameters: 24327632
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 72.96
        Top 5 Accuracy: 90.45

  - Name: tsm_r50_1x1x8_100e_8xb16_kinetics400_rgb
    Config: configs/recognition/tsm/tsm_r50_1x1x8_100e_8xb16_kinetics400_rgb.py
    In Collection: TSM
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 100
      FLOPs: 32965562368
      Parameters: 24327632
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 73.11
        Top 5 Accuracy: 90.06

  - Name: tsm_r50_1x1x16_50e_8xb16_kinetics400_rgb
    Config: configs/recognition/tsm/tsm_r50_1x1x16_50e_8xb16_kinetics400_rgb.py
    In Collection: TSM
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 100
      FLOPs: 65931124736
      Parameters: 24327632
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 74.64
        Top 5 Accuracy: 91.42

  - Name: tsm_r50_dense_1x1x8_50e_8xb16_kinetics400_rgb
    Config: configs/recognition/tsm/tsm_r50_dense_1x1x8_50e_8xb16_kinetics400_rgb.py
    In Collection: TSM
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 100
      FLOPs: 32965562368
      Parameters: 24327632
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 73.39
        Top 5 Accuracy: 90.78

  - Name: tsm_nl_embedded_gaussian_r50_1x1x8_50e_8xb16_kinetics400_rgb
    Config: configs/recognition/tsm/tsm_nl_embedded_gaussian_r50_1x1x8_50e_8xb16_kinetics400_rgb.py
    In Collection: TSM
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 100
      FLOPs: 49457811456
      Parameters: 31682000
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 74.45
        Top 5 Accuracy: 91.11

  - Name: tsm_nl_dot_product_r50_1x1x8_50e_8xb16_kinetics400_rgb
    Config: configs/recognition/tsm/tsm_nl_dot_product_r50_1x1x8_50e_8xb16_kinetics400_rgb.py
    In Collection: TSM
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 100
      FLOPs: 49457811456
      Parameters: 31682000
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 74.17
        Top 5 Accuracy: 90.95

  - Name: tsm_nl_gaussian_r50_1x1x8_50e_8xb16_kinetics400_rgb
    Config: configs/recognition/tsm/tsm_nl_gaussian_r50_1x1x8_50e_8xb16_kinetics400_rgb.py
    In Collection: TSM
    Metadata:
      Architecture: ResNet50
      Batch Size: 16
      Epochs: 100
      FLOPs: 41231355904
      Parameters: 28007888
      Pretrained: ImageNet
      Resolution: short-side 320
      Training Data: Kinetics-400
      Training Resources: 8 GPUs
    Modality: RGB
    Results:
    - Dataset: Kinetics-400
      Task: Action Recognition
      Metrics:
        Top 1 Accuracy: 73.37
        Top 5 Accuracy: 90.82
