variables:
  PARROTS_IMAGE: registry.sensetime.com/platform/product:pat20200619
  PYTORCH_IMAGE: registry.sensetime.com/eig-research/pytorch:1.3.1-cuda10.1-cudnn7-devel

stages:
  - linting
  - test
  - deploy

before_script:
  - echo $PATH
  - gcc --version
  - nvcc --version
  - python --version
  - pip --version
  - python -c "import torch; print(torch.__version__)"

linting:
  image: $PYTORCH_IMAGE
  stage: linting
  script:
    - pip install flake8 yapf isort
    - flake8 .
    - isort -rc --check-only --diff mmaction/ tools/ tests/
    - yapf -r -d mmaction/ tools/ tests/ configs

.test_template: &test_template_def
  stage: test
  script:
    - echo "Start building..."
    - conda install av -c conda-forge -y
    - pip install decord PyTurboJPEG pillow==6.2.1 pytest coverage yapf interrogate
    - pip install -e .
    - python -c "import mmaction; print(mmaction.__version__)"
    - echo "Docstring coverage..."
    - interrogate -v --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" mmaction
    - echo "Start testing..."
    - coverage run --branch --source mmaction -m pytest tests/
    - coverage report -m

test:pytorch1.3-cuda10:
  image: $PYTORCH_IMAGE
  <<: *test_template_def

test:pat0.6.0dev-cuda9:
  image: $PARROTS_IMAGE
  <<: *test_template_def

pages:
  image: $PYTORCH_IMAGE
  stage: deploy
  script:
    - pip install mmcv
    - pip install sphinx sphinx_rtd_theme recommonmark sphinx-markdown-tables
    - cd docs
    - ./add_models.sh
    - make html
    - cd ..
    - mkdir -p ./public
    - cp -r docs/_build/html/* ./public
    - ls ./public
  artifacts:
    paths:
      - public
  only:
    - master
